language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g npm-check

install:
  - npm install

script:
  - npm-check
  - echo "tests are still missing :("

